# Generated by Django 3.1.6 on 2021-03-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20210304_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.CharField(blank=True, max_length=60, verbose_name='Website Adress'),
        ),
    ]
