# Generated by Django 3.1.6 on 2021-06-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_auto_20210323_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='region',
            field=models.CharField(max_length=60, null=True, verbose_name='region'),
        ),
    ]
