# Generated by Django 3.1.6 on 2021-08-24 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_venue_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
