# Generated by Django 3.1.6 on 2021-08-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_event_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='user_image'),
        ),
    ]
