# Generated by Django 3.1.6 on 2021-09-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='default1.jpg', upload_to='user_image/%Y/%m/%d/'),
        ),
    ]
