# Generated by Django 3.1.6 on 2021-09-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_auto_20210919_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='default1.jpg', upload_to='user_images/%Y/%m/%d/'),
        ),
    ]
