# Generated by Django 3.1.6 on 2021-09-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_auto_20210919_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='default1.jpg', upload_to='uploads'),
        ),
    ]
