# Generated by Django 3.1.6 on 2021-09-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0011_auto_20210920_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
    ]
